/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// 
    /// </summary>
	public partial class Accountstatus :DBModel<Accountstatus>
	{ 
     
       /// <summary>
	   /// 账号状态id
	   /// </summary>
       private int _accountstatusid;
	   /// <summary>
	   /// 账号状态id
	   /// </summary>
	   public int AccountStatusId 
	   { 
	      get { return _accountstatusid; }
          set { SetWithNotify(value, ref _accountstatusid); }	   
	   }			  
     
       /// <summary>
	   /// 状态的名称
	   /// </summary>
       private string _accountstatusname;
	   /// <summary>
	   /// 状态的名称
	   /// </summary>
	   public string AccountStatusName 
	   { 
	      get { return _accountstatusname; }
          set { SetWithNotify(value, ref _accountstatusname); }	   
	   }			  
		
	}

}
