

/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
     using System.Collections;
     using System.Collections.Generic;
     using System.Runtime.CompilerServices;
     public partial class DBModel<T>{
         /// <summary>
         /// 属性改变列表
         /// </summary>
         public Dictionary<string, object> PropertyChangedDic = new Dictionary<string, object>();
         /// <summary>
         /// 属性改变通知
         /// </summary>
         /// <param name="propertyValue"></param>
         /// <param name="propertyName"></param>
         protected void SetWithNotify<T>(T propertyValue,ref T field,[CallerMemberName]string propertyName = "")
         {
             if (!StructuralComparisons.StructuralEqualityComparer.Equals(field, propertyValue))
             {
			     field = propertyValue;
                 PropertyChangedDic.Add(propertyName, propertyValue);
             }
         }      
     }

}
