/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// 
    /// </summary>
	public partial class Device :DBModel<Device>
	{ 
     
       /// <summary>
	   /// 设备UUID
	   /// </summary>
       private string _deviceuuid;
	   /// <summary>
	   /// 设备UUID
	   /// </summary>
	   public string DeviceUUID 
	   { 
	      get { return _deviceuuid; }
          set { SetWithNotify(value, ref _deviceuuid); }	   
	   }			  
     
       /// <summary>
	   /// 设备类型名称
	   /// </summary>
       private string _devicetypename;
	   /// <summary>
	   /// 设备类型名称
	   /// </summary>
	   public string DeviceTypeName 
	   { 
	      get { return _devicetypename; }
          set { SetWithNotify(value, ref _devicetypename); }	   
	   }			  
     
       /// <summary>
	   /// 操作系统
	   /// </summary>
       private string _os;
	   /// <summary>
	   /// 操作系统
	   /// </summary>
	   public string Os 
	   { 
	      get { return _os; }
          set { SetWithNotify(value, ref _os); }	   
	   }			  
     
       /// <summary>
	   /// 系统版本
	   /// </summary>
       private string _osver;
	   /// <summary>
	   /// 系统版本
	   /// </summary>
	   public string OsVer 
	   { 
	      get { return _osver; }
          set { SetWithNotify(value, ref _osver); }	   
	   }			  
     
       /// <summary>
	   /// 设备是否有效
	   /// </summary>
       private bool? _deviceavailable;
	   /// <summary>
	   /// 设备是否有效
	   /// </summary>
	   public bool? DeviceAvailable 
	   { 
	      get { return _deviceavailable; }
          set { SetWithNotify(value, ref _deviceavailable); }	   
	   }			  
     
       /// <summary>
	   /// 时间戳
	   /// </summary>
       private DateTime? _timestamp;
	   /// <summary>
	   /// 时间戳
	   /// </summary>
	   public DateTime? TimeStamp 
	   { 
	      get { return _timestamp; }
          set { SetWithNotify(value, ref _timestamp); }	   
	   }			  
		
	}

}
