/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// 
    /// </summary>
	public partial class Groupuser :DBModel<Groupuser>
	{ 
     
       /// <summary>
	   /// 群组关系Id
	   /// </summary>
       private int _groupid;
	   /// <summary>
	   /// 群组关系Id
	   /// </summary>
	   public int GroupId 
	   { 
	      get { return _groupid; }
          set { SetWithNotify(value, ref _groupid); }	   
	   }			  
     
       /// <summary>
	   /// 用户名
	   /// </summary>
       private string _loginname;
	   /// <summary>
	   /// 用户名
	   /// </summary>
	   public string LoginName 
	   { 
	      get { return _loginname; }
          set { SetWithNotify(value, ref _loginname); }	   
	   }			  
     
       /// <summary>
	   /// 群组关系的创建时间
	   /// </summary>
       private DateTime? _createdate;
	   /// <summary>
	   /// 群组关系的创建时间
	   /// </summary>
	   public DateTime? CreateDate 
	   { 
	      get { return _createdate; }
          set { SetWithNotify(value, ref _createdate); }	   
	   }			  
     
       /// <summary>
	   /// 群组关系的时间戳
	   /// </summary>
       private DateTime? _timestamp;
	   /// <summary>
	   /// 群组关系的时间戳
	   /// </summary>
	   public DateTime? TimeStamp 
	   { 
	      get { return _timestamp; }
          set { SetWithNotify(value, ref _timestamp); }	   
	   }			  
		
	}

}
