/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// 
    /// </summary>
	public partial class Message :DBModel<Message>
	{ 
     
       /// <summary>
	   /// 消息自增Id
	   /// </summary>
       private long _messageid;
	   /// <summary>
	   /// 消息自增Id
	   /// </summary>
	   public long MessageId 
	   { 
	      get { return _messageid; }
          set { SetWithNotify(value, ref _messageid); }	   
	   }			  
     
       /// <summary>
	   /// 用户名
	   /// </summary>
       private string _loginname;
	   /// <summary>
	   /// 用户名
	   /// </summary>
	   public string LoginName 
	   { 
	      get { return _loginname; }
          set { SetWithNotify(value, ref _loginname); }	   
	   }			  
     
       /// <summary>
	   /// 消息Id
	   /// </summary>
       private long _msgid;
	   /// <summary>
	   /// 消息Id
	   /// </summary>
	   public long MsgId 
	   { 
	      get { return _msgid; }
          set { SetWithNotify(value, ref _msgid); }	   
	   }			  
     
       /// <summary>
	   /// 发送者用户名
	   /// </summary>
       private string _fromloginname;
	   /// <summary>
	   /// 发送者用户名
	   /// </summary>
	   public string FromLoginName 
	   { 
	      get { return _fromloginname; }
          set { SetWithNotify(value, ref _fromloginname); }	   
	   }			  
     
       /// <summary>
	   /// 接收者用户名
	   /// </summary>
       private string _tologinname;
	   /// <summary>
	   /// 接收者用户名
	   /// </summary>
	   public string ToLoginName 
	   { 
	      get { return _tologinname; }
          set { SetWithNotify(value, ref _tologinname); }	   
	   }			  
     
       /// <summary>
	   /// 相关信息
	   /// </summary>
       private string _info;
	   /// <summary>
	   /// 相关信息
	   /// </summary>
	   public string Info 
	   { 
	      get { return _info; }
          set { SetWithNotify(value, ref _info); }	   
	   }			  
     
       /// <summary>
	   /// 消息
	   /// </summary>
       private string _content;
	   /// <summary>
	   /// 消息
	   /// </summary>
	   public string Content 
	   { 
	      get { return _content; }
          set { SetWithNotify(value, ref _content); }	   
	   }			  
     
       /// <summary>
	   /// 成员列表(JSON格式)
	   /// </summary>
       private string _memberlist;
	   /// <summary>
	   /// 成员列表(JSON格式)
	   /// </summary>
	   public string MemberList 
	   { 
	      get { return _memberlist; }
          set { SetWithNotify(value, ref _memberlist); }	   
	   }			  
     
       /// <summary>
	   /// 客户端生成消息Id
	   /// </summary>
       private long _clientmsgid;
	   /// <summary>
	   /// 客户端生成消息Id
	   /// </summary>
	   public long ClientMsgId 
	   { 
	      get { return _clientmsgid; }
          set { SetWithNotify(value, ref _clientmsgid); }	   
	   }			  
     
       /// <summary>
	   /// 消息创建时间戳
	   /// </summary>
       private long? _createdate;
	   /// <summary>
	   /// 消息创建时间戳
	   /// </summary>
	   public long? CreateDate 
	   { 
	      get { return _createdate; }
          set { SetWithNotify(value, ref _createdate); }	   
	   }			  
     
       /// <summary>
	   /// 消息类型
	   /// </summary>
       private int? _type;
	   /// <summary>
	   /// 消息类型
	   /// </summary>
	   public int? Type 
	   { 
	      get { return _type; }
          set { SetWithNotify(value, ref _type); }	   
	   }			  
		
	}

}
