/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// 
    /// </summary>
	public partial class Userfriend :DBModel<Userfriend>
	{ 
     
       /// <summary>
	   /// 用户名
	   /// </summary>
       private string _loginname;
	   /// <summary>
	   /// 用户名
	   /// </summary>
	   public string LoginName 
	   { 
	      get { return _loginname; }
          set { SetWithNotify(value, ref _loginname); }	   
	   }			  
     
       /// <summary>
	   /// 好友用户名
	   /// </summary>
       private string _friendloginname;
	   /// <summary>
	   /// 好友用户名
	   /// </summary>
	   public string FriendLoginName 
	   { 
	      get { return _friendloginname; }
          set { SetWithNotify(value, ref _friendloginname); }	   
	   }			  
     
       /// <summary>
	   /// 消息创建时间戳
	   /// </summary>
       private long? _createdate;
	   /// <summary>
	   /// 消息创建时间戳
	   /// </summary>
	   public long? CreateDate 
	   { 
	      get { return _createdate; }
          set { SetWithNotify(value, ref _createdate); }	   
	   }			  
     
       /// <summary>
	   /// 时间戳
	   /// </summary>
       private DateTime? _timestamp;
	   /// <summary>
	   /// 时间戳
	   /// </summary>
	   public DateTime? TimeStamp 
	   { 
	      get { return _timestamp; }
          set { SetWithNotify(value, ref _timestamp); }	   
	   }			  
		
	}

}
