/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// 
    /// </summary>
	public partial class Userlogin :DBModel<Userlogin>
	{ 
     
       /// <summary>
	   /// 登陆状态id
	   /// </summary>
       private int _id;
	   /// <summary>
	   /// 登陆状态id
	   /// </summary>
	   public int Id 
	   { 
	      get { return _id; }
          set { SetWithNotify(value, ref _id); }	   
	   }			  
     
       /// <summary>
	   /// 用户名
	   /// </summary>
       private string _loginname;
	   /// <summary>
	   /// 用户名
	   /// </summary>
	   public string LoginName 
	   { 
	      get { return _loginname; }
          set { SetWithNotify(value, ref _loginname); }	   
	   }			  
     
       /// <summary>
	   /// 设备UUID
	   /// </summary>
       private string _deviceuuid;
	   /// <summary>
	   /// 设备UUID
	   /// </summary>
	   public string DeviceUUID 
	   { 
	      get { return _deviceuuid; }
          set { SetWithNotify(value, ref _deviceuuid); }	   
	   }			  
     
       /// <summary>
	   /// 登陆授权的token
	   /// </summary>
       private string _authtoken;
	   /// <summary>
	   /// 登陆授权的token
	   /// </summary>
	   public string AuthToken 
	   { 
	      get { return _authtoken; }
          set { SetWithNotify(value, ref _authtoken); }	   
	   }			  
     
       /// <summary>
	   /// 时间戳
	   /// </summary>
       private DateTime? _timestamp;
	   /// <summary>
	   /// 时间戳
	   /// </summary>
	   public DateTime? TimeStamp 
	   { 
	      get { return _timestamp; }
          set { SetWithNotify(value, ref _timestamp); }	   
	   }			  
     
       /// <summary>
	   /// 客户端IP
	   /// </summary>
       private string _loginip;
	   /// <summary>
	   /// 客户端IP
	   /// </summary>
	   public string LoginIP 
	   { 
	      get { return _loginip; }
          set { SetWithNotify(value, ref _loginip); }	   
	   }			  
     
       /// <summary>
	   /// 登客户端端口
	   /// </summary>
       private string _loginport;
	   /// <summary>
	   /// 登客户端端口
	   /// </summary>
	   public string LoginPort 
	   { 
	      get { return _loginport; }
          set { SetWithNotify(value, ref _loginport); }	   
	   }			  
     
       /// <summary>
	   /// 服务端IP
	   /// </summary>
       private string _wsip;
	   /// <summary>
	   /// 服务端IP
	   /// </summary>
	   public string WSIP 
	   { 
	      get { return _wsip; }
          set { SetWithNotify(value, ref _wsip); }	   
	   }			  
     
       /// <summary>
	   /// 服务端端口
	   /// </summary>
       private string _wsport;
	   /// <summary>
	   /// 服务端端口
	   /// </summary>
	   public string WSPort 
	   { 
	      get { return _wsport; }
          set { SetWithNotify(value, ref _wsport); }	   
	   }			  
     
       /// <summary>
	   /// 登陆状态
	   /// </summary>
       private int? _loginstate;
	   /// <summary>
	   /// 登陆状态
	   /// </summary>
	   public int? LoginState 
	   { 
	      get { return _loginstate; }
          set { SetWithNotify(value, ref _loginstate); }	   
	   }			  
		
	}

}
