/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// 
    /// </summary>
	public partial class Usersettings :DBModel<Usersettings>
	{ 
     
       /// <summary>
	   /// 用户个人设置id
	   /// </summary>
       private int _usersettingsid;
	   /// <summary>
	   /// 用户个人设置id
	   /// </summary>
	   public int UserSettingsId 
	   { 
	      get { return _usersettingsid; }
          set { SetWithNotify(value, ref _usersettingsid); }	   
	   }			  
     
       /// <summary>
	   /// 用户名
	   /// </summary>
       private string _loginname;
	   /// <summary>
	   /// 用户名
	   /// </summary>
	   public string LoginName 
	   { 
	      get { return _loginname; }
          set { SetWithNotify(value, ref _loginname); }	   
	   }			  
     
       /// <summary>
	   /// 设置的用户名
	   /// </summary>
       private string _setloginname;
	   /// <summary>
	   /// 设置的用户名
	   /// </summary>
	   public string SetLoginName 
	   { 
	      get { return _setloginname; }
          set { SetWithNotify(value, ref _setloginname); }	   
	   }			  
     
       /// <summary>
	   /// 备注
	   /// </summary>
       private string _remark;
	   /// <summary>
	   /// 备注
	   /// </summary>
	   public string Remark 
	   { 
	      get { return _remark; }
          set { SetWithNotify(value, ref _remark); }	   
	   }			  
     
       /// <summary>
	   /// 允许消息提醒
	   /// </summary>
       private bool _allowremind;
	   /// <summary>
	   /// 允许消息提醒
	   /// </summary>
	   public bool AllowRemind 
	   { 
	      get { return _allowremind; }
          set { SetWithNotify(value, ref _allowremind); }	   
	   }			  
     
       /// <summary>
	   /// 时间戳
	   /// </summary>
       private DateTime? _timestamp;
	   /// <summary>
	   /// 时间戳
	   /// </summary>
	   public DateTime? TimeStamp 
	   { 
	      get { return _timestamp; }
          set { SetWithNotify(value, ref _timestamp); }	   
	   }			  
		
	}

}
