/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// 
    /// </summary>
	public partial class Usermaxrev :DBModel<Usermaxrev>
	{ 
     
       /// <summary>
	   /// 用户名
	   /// </summary>
       private string _loginname;
	   /// <summary>
	   /// 用户名
	   /// </summary>
	   public string LoginName 
	   { 
	      get { return _loginname; }
          set { SetWithNotify(value, ref _loginname); }	   
	   }			  
     
       /// <summary>
	   /// 最后接收的消息id
	   /// </summary>
       private long? _maxmsgid;
	   /// <summary>
	   /// 最后接收的消息id
	   /// </summary>
	   public long? MaxMsgId 
	   { 
	      get { return _maxmsgid; }
          set { SetWithNotify(value, ref _maxmsgid); }	   
	   }			  
		
	}

}
