/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// VIEW
    /// </summary>
	public partial class Vw_Department :DBModel<Vw_Department>
	{ 
     
       /// <summary>
	   /// 部门名称
	   /// </summary>
       private string _deptname;
	   /// <summary>
	   /// 部门名称
	   /// </summary>
	   public string DeptName 
	   { 
	      get { return _deptname; }
          set { SetWithNotify(value, ref _deptname); }	   
	   }			  
     
       /// <summary>
	   /// 父部门名称
	   /// </summary>
       private string _parentdeptname;
	   /// <summary>
	   /// 父部门名称
	   /// </summary>
	   public string ParentDeptName 
	   { 
	      get { return _parentdeptname; }
          set { SetWithNotify(value, ref _parentdeptname); }	   
	   }			  
		
	}

}
