/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// VIEW
    /// </summary>
	public partial class Vw_Userdevice :DBModel<Vw_Userdevice>
	{ 
     
       /// <summary>
	   /// 设备UUID
	   /// </summary>
       private string _deviceuuid;
	   /// <summary>
	   /// 设备UUID
	   /// </summary>
	   public string DeviceUUID 
	   { 
	      get { return _deviceuuid; }
          set { SetWithNotify(value, ref _deviceuuid); }	   
	   }			  
     
       /// <summary>
	   /// 设备类型名称
	   /// </summary>
       private string _devicetypename;
	   /// <summary>
	   /// 设备类型名称
	   /// </summary>
	   public string DeviceTypeName 
	   { 
	      get { return _devicetypename; }
          set { SetWithNotify(value, ref _devicetypename); }	   
	   }			  
     
       /// <summary>
	   /// 操作系统
	   /// </summary>
       private string _os;
	   /// <summary>
	   /// 操作系统
	   /// </summary>
	   public string Os 
	   { 
	      get { return _os; }
          set { SetWithNotify(value, ref _os); }	   
	   }			  
     
       /// <summary>
	   /// 系统版本
	   /// </summary>
       private string _osver;
	   /// <summary>
	   /// 系统版本
	   /// </summary>
	   public string OsVer 
	   { 
	      get { return _osver; }
          set { SetWithNotify(value, ref _osver); }	   
	   }			  
     
       /// <summary>
	   /// 设备是否有效
	   /// </summary>
       private bool? _deviceavailable;
	   /// <summary>
	   /// 设备是否有效
	   /// </summary>
	   public bool? DeviceAvailable 
	   { 
	      get { return _deviceavailable; }
          set { SetWithNotify(value, ref _deviceavailable); }	   
	   }			  
     
       /// <summary>
	   /// 用户名
	   /// </summary>
       private string _loginname;
	   /// <summary>
	   /// 用户名
	   /// </summary>
	   public string LoginName 
	   { 
	      get { return _loginname; }
          set { SetWithNotify(value, ref _loginname); }	   
	   }			  
     
       /// <summary>
	   /// 登陆授权的token
	   /// </summary>
       private string _authtoken;
	   /// <summary>
	   /// 登陆授权的token
	   /// </summary>
	   public string AuthToken 
	   { 
	      get { return _authtoken; }
          set { SetWithNotify(value, ref _authtoken); }	   
	   }			  
     
       /// <summary>
	   /// 登录名
	   /// </summary>
       private string _anothername;
	   /// <summary>
	   /// 登录名
	   /// </summary>
	   public string AnotherName 
	   { 
	      get { return _anothername; }
          set { SetWithNotify(value, ref _anothername); }	   
	   }			  
     
       /// <summary>
	   /// 服务端IP
	   /// </summary>
       private string _wsip;
	   /// <summary>
	   /// 服务端IP
	   /// </summary>
	   public string WSIP 
	   { 
	      get { return _wsip; }
          set { SetWithNotify(value, ref _wsip); }	   
	   }			  
     
       /// <summary>
	   /// 服务端端口
	   /// </summary>
       private string _wsport;
	   /// <summary>
	   /// 服务端端口
	   /// </summary>
	   public string WSPort 
	   { 
	      get { return _wsport; }
          set { SetWithNotify(value, ref _wsport); }	   
	   }			  
     
       /// <summary>
	   /// 登陆状态
	   /// </summary>
       private int? _loginstate;
	   /// <summary>
	   /// 登陆状态
	   /// </summary>
	   public int? LoginState 
	   { 
	      get { return _loginstate; }
          set { SetWithNotify(value, ref _loginstate); }	   
	   }			  
		
	}

}
