/*
<auto-generated>
 此代码由T4模板自动生成
 生成时间 2014-10-29 22:20:33 by Auto Generated
*/
namespace Model
{
	using System;

    /// <summary>
    /// VIEW
    /// </summary>
	public partial class Vw_Userstatus :DBModel<Vw_Userstatus>
	{ 
     
       /// <summary>
	   /// 用户名
	   /// </summary>
       private string _loginname;
	   /// <summary>
	   /// 用户名
	   /// </summary>
	   public string LoginName 
	   { 
	      get { return _loginname; }
          set { SetWithNotify(value, ref _loginname); }	   
	   }			  
     
       /// <summary>
	   /// 状态的名称
	   /// </summary>
       private string _accountstatusname;
	   /// <summary>
	   /// 状态的名称
	   /// </summary>
	   public string AccountStatusName 
	   { 
	      get { return _accountstatusname; }
          set { SetWithNotify(value, ref _accountstatusname); }	   
	   }			  
     
       /// <summary>
	   /// 账号状态id
	   /// </summary>
       private int _accountstatusid;
	   /// <summary>
	   /// 账号状态id
	   /// </summary>
	   public int AccountStatusId 
	   { 
	      get { return _accountstatusid; }
          set { SetWithNotify(value, ref _accountstatusid); }	   
	   }			  
     
       /// <summary>
	   /// 父部门名称
	   /// </summary>
       private string _parentdeptname;
	   /// <summary>
	   /// 父部门名称
	   /// </summary>
	   public string ParentDeptName 
	   { 
	      get { return _parentdeptname; }
          set { SetWithNotify(value, ref _parentdeptname); }	   
	   }			  
     
       /// <summary>
	   /// 真实名字
	   /// </summary>
       private string _realname;
	   /// <summary>
	   /// 真实名字
	   /// </summary>
	   public string RealName 
	   { 
	      get { return _realname; }
          set { SetWithNotify(value, ref _realname); }	   
	   }			  
     
       /// <summary>
	   /// 职位
	   /// </summary>
       private string _position;
	   /// <summary>
	   /// 职位
	   /// </summary>
	   public string Position 
	   { 
	      get { return _position; }
          set { SetWithNotify(value, ref _position); }	   
	   }			  
     
       /// <summary>
	   /// 手机号
	   /// </summary>
       private string _mobilephone;
	   /// <summary>
	   /// 手机号
	   /// </summary>
	   public string mobilePhone 
	   { 
	      get { return _mobilephone; }
          set { SetWithNotify(value, ref _mobilephone); }	   
	   }			  
		
	}

}
